Test the import

In [99]:
from pymongo import MongoClient
import cnfg
import tweepy
import json
from pymongo import MongoClient
import sys
import pickle
import os
import pandas as pd
import re
from pprint import pprint
from datetime import datetime

Let's create our Mongo Client, using the port that we specified in our ssh tunnel

In [100]:
client = MongoClient(port=12345) # this is the port set by the SSH tunnel
db = client.electionnight

In [101]:
# print collection names
print(db.list_collection_names())

['election_tweets']

In [40]:
ckey = 'g9eKDq1iB00hJkJgrAekA1YbD'
consumer_secret = 'T0CMdbHI9EdQqJ9tMRFaW2kDS3YrE5wVpHAeLdST3d8yerwG6p'
access_token_key = '1060277265060134914-dpegkpggdkdvT6hvoLxA59tVp94bSa'
access_token_secret = 'IJkmqN66WqqlYA04EDDVGOSYfCoDk9DOgEueaC0XOTBKx'

In [41]:
auth = tweepy.OAuthHandler(ckey, consumer_secret)
auth.set_access_token(access_token_key, access_token_secret)

api = tweepy.API(auth,wait_on_rate_limit=True,
                   wait_on_rate_limit_notify=True)
if (not api):
    print ("Can't Authenticate")
    sys.exit(-1)

collection = db.election_tweets
searchQuery = ('#ElectionNight OR #Midterms2018')  # Search for tweets containing any of these terms
maxTweets = 70000 # Some arbitrary large number
tweetsPerQry = 180  # this is the max the API permits with OAuth
language = 'en' # only get tweets in english
tweetmode = 'extended' # tweets greaterthan 140 char are returned


# If results from a specific ID onwards are reqd, set since_id to that ID.
# else default to no lower limit, go as far back as API allows
sinceId = None

# If results required are only below a specific ID, set max_id to that ID.
# else default to no upper limit, start from the most recent tweet matching the search query.
max_id = -1000

tweetCount = 0
print("Downloading max {0} tweets".format(maxTweets))

# Stream tweets according to user-defined max_id and sinceId
while tweetCount < maxTweets:
    try:
        if (max_id <= 0):
            if (not sinceId):
                new_tweets = api.search(q=searchQuery, count=tweetsPerQry, lang= language, tweet_mode = tweetmode)
            else:
                new_tweets = api.search(q=searchQuery, count=tweetsPerQry,
                                        since_id=sinceId, lang= language, tweet_mode = tweetmode)
        else:
            if (not sinceId):
                new_tweets = api.search(q=searchQuery, count=tweetsPerQry,
                                        max_id=str(max_id - 1), lang= language, tweet_mode = tweetmode)
            else:
                new_tweets = api.search(q=searchQuery, count=tweetsPerQry,
                                        max_id=str(max_id - 1),
                                        since_id=sinceId, lang= language, tweet_mode = tweetmode)
        if not new_tweets:
            print("No more tweets found")
            break
            
# Load tweets into MongoDB
        for tweet in new_tweets:
            collection.insert(tweet._json)
        tweetCount += len(new_tweets)
        print("Downloaded {0} tweets".format(tweetCount))
        max_id = new_tweets[-1].id
    except tweepy.TweepError as e:
        # Just exit if any error
        print("some error : " + str(e))
        break

print ("Downloaded {0} tweets, Saved to MongoDB election night".format(tweetCount))

Downloading max 70000 tweets

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:52: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.

Downloaded 100 tweets
Downloaded 200 tweets
Downloaded 300 tweets
Downloaded 400 tweets
Downloaded 500 tweets
Downloaded 600 tweets
Downloaded 700 tweets
Downloaded 800 tweets
Downloaded 900 tweets
Downloaded 1000 tweets
Downloaded 1100 tweets
Downloaded 1200 tweets
Downloaded 1300 tweets
Downloaded 1400 tweets
Downloaded 1500 tweets
Downloaded 1600 tweets
Downloaded 1700 tweets
Downloaded 1800 tweets
Downloaded 1900 tweets
Downloaded 2000 tweets
Downloaded 2100 tweets
Downloaded 2200 tweets
Downloaded 2300 tweets
Downloaded 2400 tweets
Downloaded 2500 tweets
Downloaded 2600 tweets
Downloaded 2700 tweets
Downloaded 2800 tweets
Downloaded 2900 tweets
Downloaded 3000 tweets
Downloaded 3100 tweets
Downloaded 3200 tweets
Downloaded 3300 tweets
Downloaded 3400 tweets
Downloaded 3500 tweets
Downloaded 3600 tweets
Downloaded 3700 tweets
Downloaded 3800 tweets
Downloaded 3900 tweets
Downloaded 4000 tweets
Downloaded 4100 tweets
Downloaded 4200 tweets
Downloaded 4300 tweets
Downloaded 4400 tweets
Downloaded 4500 tweets
Downloaded 4600 tweets
Downloaded 4700 tweets
Downloaded 4800 tweets
Downloaded 4900 tweets
Downloaded 5000 tweets
Downloaded 5100 tweets
Downloaded 5200 tweets
Downloaded 5300 tweets
Downloaded 5400 tweets
Downloaded 5500 tweets
Downloaded 5600 tweets
Downloaded 5700 tweets
Downloaded 5800 tweets
Downloaded 5900 tweets
Downloaded 6000 tweets
Downloaded 6100 tweets
Downloaded 6200 tweets
Downloaded 6300 tweets
Downloaded 6400 tweets
Downloaded 6500 tweets
Downloaded 6600 tweets
Downloaded 6700 tweets
Downloaded 6800 tweets
Downloaded 6900 tweets
Downloaded 7000 tweets
Downloaded 7100 tweets
Downloaded 7200 tweets
Downloaded 7300 tweets
Downloaded 7395 tweets
Downloaded 7495 tweets
Downloaded 7595 tweets
Downloaded 7695 tweets
Downloaded 7795 tweets
Downloaded 7895 tweets
Downloaded 7995 tweets
Downloaded 8095 tweets
Downloaded 8195 tweets
Downloaded 8295 tweets
Downloaded 8395 tweets
Downloaded 8495 tweets
Downloaded 8595 tweets
Downloaded 8695 tweets
Downloaded 8795 tweets
Downloaded 8895 tweets
Downloaded 8995 tweets
Downloaded 9094 tweets
Downloaded 9194 tweets
Downloaded 9294 tweets
Downloaded 9394 tweets
Downloaded 9494 tweets
Downloaded 9594 tweets
Downloaded 9694 tweets
Downloaded 9793 tweets
Downloaded 9893 tweets
Downloaded 9993 tweets
Downloaded 10093 tweets
Downloaded 10193 tweets
Downloaded 10293 tweets
Downloaded 10393 tweets
Downloaded 10487 tweets
Downloaded 10583 tweets
Downloaded 10683 tweets
Downloaded 10783 tweets
Downloaded 10883 tweets
Downloaded 10983 tweets
Downloaded 11083 tweets
Downloaded 11183 tweets
Downloaded 11282 tweets
Downloaded 11382 tweets
Downloaded 11482 tweets
Downloaded 11582 tweets
Downloaded 11682 tweets
Downloaded 11782 tweets
Downloaded 11880 tweets
Downloaded 11980 tweets
Downloaded 12080 tweets
Downloaded 12180 tweets
Downloaded 12280 tweets
Downloaded 12380 tweets
Downloaded 12480 tweets
Downloaded 12580 tweets
Downloaded 12680 tweets
Downloaded 12780 tweets
Downloaded 12880 tweets
Downloaded 12980 tweets
Downloaded 13080 tweets
Downloaded 13180 tweets
Downloaded 13280 tweets
Downloaded 13380 tweets
Downloaded 13480 tweets
Downloaded 13580 tweets
Downloaded 13680 tweets
Downloaded 13780 tweets
Downloaded 13880 tweets
Downloaded 13980 tweets
Downloaded 14080 tweets
Downloaded 14180 tweets
Downloaded 14280 tweets
Downloaded 14380 tweets
Downloaded 14480 tweets
Downloaded 14580 tweets
Downloaded 14680 tweets
Downloaded 14780 tweets
Downloaded 14880 tweets
Downloaded 14980 tweets
Downloaded 15076 tweets
Downloaded 15176 tweets
Downloaded 15274 tweets
Downloaded 15374 tweets
Downloaded 15474 tweets
Downloaded 15574 tweets
Downloaded 15669 tweets
Downloaded 15769 tweets
Downloaded 15869 tweets
Downloaded 15969 tweets
Downloaded 16069 tweets
Downloaded 16169 tweets
Downloaded 16267 tweets
Downloaded 16365 tweets
Downloaded 16463 tweets
Downloaded 16562 tweets
Downloaded 16662 tweets
Downloaded 16762 tweets
Downloaded 16862 tweets
Downloaded 16962 tweets
Downloaded 17062 tweets
Downloaded 17161 tweets
Downloaded 17261 tweets
Downloaded 17361 tweets
Downloaded 17461 tweets
Downloaded 17561 tweets
Downloaded 17661 tweets
Downloaded 17761 tweets
Downloaded 17861 tweets

Rate limit reached. Sleeping for: 576

Downloaded 17961 tweets
Downloaded 18061 tweets
Downloaded 18161 tweets
Downloaded 18261 tweets
Downloaded 18361 tweets
Downloaded 18461 tweets
Downloaded 18561 tweets
Downloaded 18655 tweets
Downloaded 18746 tweets
Downloaded 18846 tweets
Downloaded 18940 tweets
Downloaded 19040 tweets
Downloaded 19140 tweets
Downloaded 19240 tweets
Downloaded 19340 tweets
Downloaded 19440 tweets
Downloaded 19540 tweets
Downloaded 19638 tweets
Downloaded 19738 tweets
Downloaded 19838 tweets
Downloaded 19938 tweets
Downloaded 20035 tweets
Downloaded 20135 tweets
Downloaded 20235 tweets
Downloaded 20335 tweets
Downloaded 20435 tweets
Downloaded 20535 tweets
Downloaded 20635 tweets
Downloaded 20735 tweets
Downloaded 20835 tweets
Downloaded 20935 tweets
Downloaded 21035 tweets
Downloaded 21135 tweets
Downloaded 21228 tweets
Downloaded 21328 tweets
Downloaded 21428 tweets
Downloaded 21528 tweets
Downloaded 21627 tweets
Downloaded 21727 tweets
Downloaded 21827 tweets
Downloaded 21927 tweets
Downloaded 22022 tweets
Downloaded 22122 tweets
Downloaded 22222 tweets
Downloaded 22322 tweets
Downloaded 22422 tweets
Downloaded 22522 tweets
Downloaded 22622 tweets
Downloaded 22719 tweets
Downloaded 22819 tweets
Downloaded 22914 tweets
Downloaded 23014 tweets
Downloaded 23109 tweets
Downloaded 23208 tweets
Downloaded 23290 tweets
Downloaded 23388 tweets
Downloaded 23488 tweets
Downloaded 23587 tweets
Downloaded 23684 tweets
Downloaded 23782 tweets
Downloaded 23879 tweets
Downloaded 23979 tweets
Downloaded 24079 tweets
Downloaded 24176 tweets
Downloaded 24273 tweets
Downloaded 24371 tweets
Downloaded 24470 tweets
Downloaded 24562 tweets
Downloaded 24658 tweets
Downloaded 24756 tweets
Downloaded 24849 tweets
Downloaded 24944 tweets
Downloaded 25041 tweets
Downloaded 25138 tweets
Downloaded 25238 tweets
Downloaded 25338 tweets
Downloaded 25430 tweets
Downloaded 25530 tweets
Downloaded 25625 tweets
Downloaded 25725 tweets
Downloaded 25825 tweets
Downloaded 25925 tweets
Downloaded 26021 tweets
Downloaded 26116 tweets
Downloaded 26208 tweets
Downloaded 26300 tweets
Downloaded 26400 tweets
Downloaded 26500 tweets
Downloaded 26592 tweets
Downloaded 26688 tweets
Downloaded 26788 tweets
Downloaded 26888 tweets
Downloaded 26988 tweets
Downloaded 27088 tweets
Downloaded 27188 tweets
Downloaded 27284 tweets
Downloaded 27384 tweets
Downloaded 27484 tweets
Downloaded 27584 tweets
Downloaded 27684 tweets
Downloaded 27784 tweets
Downloaded 27883 tweets
Downloaded 27983 tweets
Downloaded 28083 tweets
Downloaded 28183 tweets
Downloaded 28283 tweets
Downloaded 28383 tweets
Downloaded 28483 tweets
Downloaded 28583 tweets
Downloaded 28683 tweets
Downloaded 28783 tweets
Downloaded 28883 tweets
Downloaded 28983 tweets
Downloaded 29083 tweets
Downloaded 29181 tweets
Downloaded 29281 tweets
Downloaded 29381 tweets
Downloaded 29481 tweets
Downloaded 29581 tweets
Downloaded 29681 tweets
Downloaded 29781 tweets
Downloaded 29881 tweets
Downloaded 29981 tweets
Downloaded 30072 tweets
Downloaded 30172 tweets
Downloaded 30272 tweets
Downloaded 30372 tweets
Downloaded 30472 tweets
Downloaded 30572 tweets
Downloaded 30672 tweets
Downloaded 30772 tweets
Downloaded 30872 tweets
Downloaded 30972 tweets
Downloaded 31069 tweets
Downloaded 31167 tweets
Downloaded 31267 tweets
Downloaded 31367 tweets
Downloaded 31466 tweets
Downloaded 31566 tweets
Downloaded 31666 tweets
Downloaded 31761 tweets
Downloaded 31857 tweets
Downloaded 31957 tweets
Downloaded 32047 tweets
Downloaded 32145 tweets
Downloaded 32243 tweets
Downloaded 32343 tweets
Downloaded 32443 tweets
Downloaded 32543 tweets
Downloaded 32643 tweets
Downloaded 32743 tweets
Downloaded 32843 tweets
Downloaded 32943 tweets
Downloaded 33043 tweets
Downloaded 33143 tweets
Downloaded 33243 tweets
Downloaded 33338 tweets
Downloaded 33438 tweets
Downloaded 33538 tweets
Downloaded 33638 tweets
Downloaded 33738 tweets
Downloaded 33838 tweets
Downloaded 33938 tweets
Downloaded 34038 tweets
Downloaded 34138 tweets
Downloaded 34238 tweets
Downloaded 34338 tweets
Downloaded 34438 tweets
Downloaded 34538 tweets
Downloaded 34638 tweets
Downloaded 34738 tweets
Downloaded 34838 tweets
Downloaded 34938 tweets
Downloaded 35038 tweets
Downloaded 35134 tweets
Downloaded 35234 tweets
Downloaded 35334 tweets
Downloaded 35434 tweets
Downloaded 35534 tweets
Downloaded 35634 tweets

Rate limit reached. Sleeping for: 555

Downloaded 35734 tweets
Downloaded 35834 tweets
Downloaded 35934 tweets
Downloaded 36034 tweets
Downloaded 36134 tweets
Downloaded 36234 tweets
Downloaded 36334 tweets
Downloaded 36434 tweets
Downloaded 36534 tweets
Downloaded 36634 tweets
Downloaded 36734 tweets
Downloaded 36834 tweets
Downloaded 36934 tweets
Downloaded 37034 tweets
Downloaded 37134 tweets
Downloaded 37234 tweets
Downloaded 37334 tweets
Downloaded 37434 tweets
Downloaded 37534 tweets
Downloaded 37634 tweets
Downloaded 37734 tweets
Downloaded 37834 tweets
Downloaded 37934 tweets
Downloaded 38034 tweets
Downloaded 38134 tweets
Downloaded 38234 tweets
Downloaded 38334 tweets
Downloaded 38434 tweets
Downloaded 38534 tweets
Downloaded 38634 tweets
Downloaded 38734 tweets
Downloaded 38833 tweets
Downloaded 38933 tweets
Downloaded 39033 tweets
Downloaded 39133 tweets
Downloaded 39233 tweets
Downloaded 39333 tweets
Downloaded 39433 tweets
Downloaded 39533 tweets
Downloaded 39633 tweets
Downloaded 39733 tweets
Downloaded 39833 tweets
Downloaded 39933 tweets
Downloaded 40029 tweets
Downloaded 40127 tweets
Downloaded 40227 tweets
Downloaded 40324 tweets
Downloaded 40424 tweets
Downloaded 40522 tweets
Downloaded 40622 tweets
Downloaded 40722 tweets
Downloaded 40822 tweets
Downloaded 40922 tweets
Downloaded 41022 tweets
Downloaded 41122 tweets
Downloaded 41222 tweets
Downloaded 41322 tweets
Downloaded 41422 tweets
Downloaded 41522 tweets
Downloaded 41622 tweets
Downloaded 41721 tweets
Downloaded 41821 tweets
Downloaded 41921 tweets
Downloaded 42021 tweets
Downloaded 42121 tweets
Downloaded 42221 tweets
Downloaded 42321 tweets
Downloaded 42420 tweets
Downloaded 42520 tweets
Downloaded 42619 tweets
Downloaded 42719 tweets
Downloaded 42812 tweets
Downloaded 42912 tweets
Downloaded 43012 tweets
Downloaded 43112 tweets
Downloaded 43212 tweets
Downloaded 43312 tweets
Downloaded 43412 tweets
Downloaded 43512 tweets
Downloaded 43612 tweets
Downloaded 43712 tweets
Downloaded 43812 tweets
Downloaded 43912 tweets
Downloaded 44012 tweets
Downloaded 44112 tweets
Downloaded 44212 tweets
Downloaded 44312 tweets
Downloaded 44412 tweets
Downloaded 44512 tweets
Downloaded 44612 tweets
Downloaded 44712 tweets
Downloaded 44812 tweets
Downloaded 44912 tweets
Downloaded 45012 tweets
Downloaded 45112 tweets
Downloaded 45210 tweets
Downloaded 45310 tweets
Downloaded 45410 tweets
Downloaded 45510 tweets
Downloaded 45610 tweets
Downloaded 45710 tweets
Downloaded 45810 tweets
Downloaded 45906 tweets
Downloaded 46006 tweets
Downloaded 46104 tweets
Downloaded 46204 tweets
Downloaded 46304 tweets
Downloaded 46404 tweets
Downloaded 46502 tweets
Downloaded 46602 tweets
Downloaded 46696 tweets
Downloaded 46795 tweets
Downloaded 46893 tweets
Downloaded 46993 tweets
Downloaded 47089 tweets
Downloaded 47186 tweets
Downloaded 47286 tweets
Downloaded 47386 tweets
Downloaded 47486 tweets
Downloaded 47586 tweets
Downloaded 47686 tweets
Downloaded 47786 tweets
Downloaded 47884 tweets
Downloaded 47984 tweets
Downloaded 48084 tweets
Downloaded 48184 tweets
Downloaded 48284 tweets
Downloaded 48384 tweets
Downloaded 48484 tweets
Downloaded 48584 tweets
Downloaded 48684 tweets
Downloaded 48784 tweets
Downloaded 48884 tweets
Downloaded 48984 tweets
Downloaded 49076 tweets
Downloaded 49176 tweets
Downloaded 49276 tweets
Downloaded 49376 tweets
Downloaded 49476 tweets
Downloaded 49576 tweets
Downloaded 49676 tweets
Downloaded 49776 tweets
Downloaded 49876 tweets
Downloaded 49976 tweets
Downloaded 50076 tweets
Downloaded 50176 tweets
Downloaded 50276 tweets
Downloaded 50376 tweets
Downloaded 50476 tweets
Downloaded 50576 tweets
Downloaded 50674 tweets
Downloaded 50774 tweets
Downloaded 50874 tweets
Downloaded 50974 tweets
Downloaded 51074 tweets
Downloaded 51174 tweets
Downloaded 51274 tweets
Downloaded 51374 tweets
Downloaded 51474 tweets
Downloaded 51574 tweets
Downloaded 51674 tweets
Downloaded 51771 tweets
Downloaded 51871 tweets
Downloaded 51971 tweets
Downloaded 52071 tweets
Downloaded 52171 tweets
Downloaded 52271 tweets
Downloaded 52371 tweets
Downloaded 52471 tweets
Downloaded 52571 tweets
Downloaded 52671 tweets
Downloaded 52771 tweets
Downloaded 52871 tweets
Downloaded 52971 tweets
Downloaded 53071 tweets
Downloaded 53171 tweets
Downloaded 53271 tweets
Downloaded 53371 tweets
Downloaded 53471 tweets
Downloaded 53571 tweets

Rate limit reached. Sleeping for: 568

Downloaded 53671 tweets
Downloaded 53771 tweets
Downloaded 53871 tweets
Downloaded 53971 tweets
Downloaded 54071 tweets
Downloaded 54171 tweets
Downloaded 54271 tweets
Downloaded 54371 tweets
Downloaded 54471 tweets
Downloaded 54571 tweets
Downloaded 54671 tweets
Downloaded 54771 tweets
Downloaded 54869 tweets
Downloaded 54969 tweets
Downloaded 55069 tweets
Downloaded 55169 tweets
Downloaded 55268 tweets
Downloaded 55368 tweets
Downloaded 55468 tweets
Downloaded 55568 tweets
Downloaded 55665 tweets
Downloaded 55765 tweets
Downloaded 55865 tweets
Downloaded 55958 tweets
Downloaded 56058 tweets
Downloaded 56158 tweets
Downloaded 56258 tweets
Downloaded 56358 tweets
Downloaded 56458 tweets
Downloaded 56558 tweets
Downloaded 56658 tweets
Downloaded 56758 tweets
Downloaded 56858 tweets
Downloaded 56958 tweets
Downloaded 57058 tweets
Downloaded 57158 tweets
Downloaded 57258 tweets
Downloaded 57358 tweets
Downloaded 57458 tweets
Downloaded 57558 tweets
Downloaded 57658 tweets
Downloaded 57758 tweets
Downloaded 57858 tweets
Downloaded 57958 tweets
Downloaded 58058 tweets
Downloaded 58158 tweets
Downloaded 58253 tweets
Downloaded 58353 tweets
Downloaded 58453 tweets
Downloaded 58553 tweets
Downloaded 58653 tweets
Downloaded 58753 tweets
Downloaded 58853 tweets
Downloaded 58953 tweets
Downloaded 59053 tweets
Downloaded 59153 tweets
Downloaded 59253 tweets
Downloaded 59347 tweets
Downloaded 59447 tweets
Downloaded 59547 tweets
Downloaded 59647 tweets
Downloaded 59747 tweets
Downloaded 59847 tweets
Downloaded 59947 tweets
Downloaded 60047 tweets
Downloaded 60147 tweets
Downloaded 60246 tweets
Downloaded 60346 tweets
Downloaded 60446 tweets
Downloaded 60546 tweets
Downloaded 60642 tweets
Downloaded 60742 tweets
Downloaded 60842 tweets
Downloaded 60942 tweets
Downloaded 61042 tweets
Downloaded 61142 tweets
Downloaded 61242 tweets
Downloaded 61342 tweets
Downloaded 61442 tweets
Downloaded 61542 tweets
Downloaded 61642 tweets
Downloaded 61742 tweets
Downloaded 61842 tweets
Downloaded 61942 tweets
Downloaded 62042 tweets
Downloaded 62142 tweets
Downloaded 62242 tweets
Downloaded 62342 tweets
Downloaded 62442 tweets
Downloaded 62542 tweets
Downloaded 62642 tweets
Downloaded 62742 tweets
Downloaded 62842 tweets
Downloaded 62942 tweets
Downloaded 63042 tweets
Downloaded 63142 tweets
Downloaded 63242 tweets
Downloaded 63342 tweets
Downloaded 63442 tweets
Downloaded 63542 tweets
Downloaded 63642 tweets
Downloaded 63740 tweets
Downloaded 63840 tweets
Downloaded 63940 tweets
Downloaded 64040 tweets
Downloaded 64138 tweets
Downloaded 64238 tweets
Downloaded 64338 tweets
Downloaded 64437 tweets
Downloaded 64537 tweets
Downloaded 64637 tweets
Downloaded 64737 tweets
Downloaded 64837 tweets
Downloaded 64937 tweets
Downloaded 65037 tweets
Downloaded 65137 tweets
Downloaded 65237 tweets
Downloaded 65337 tweets
Downloaded 65437 tweets
Downloaded 65537 tweets
Downloaded 65637 tweets
Downloaded 65737 tweets
Downloaded 65837 tweets
Downloaded 65937 tweets
Downloaded 66037 tweets
Downloaded 66137 tweets
Downloaded 66237 tweets
Downloaded 66337 tweets
Downloaded 66437 tweets
Downloaded 66537 tweets
Downloaded 66637 tweets
Downloaded 66737 tweets
Downloaded 66837 tweets
Downloaded 66937 tweets
Downloaded 67037 tweets
Downloaded 67137 tweets
Downloaded 67237 tweets
Downloaded 67337 tweets
Downloaded 67437 tweets
Downloaded 67537 tweets
Downloaded 67637 tweets
Downloaded 67737 tweets
Downloaded 67837 tweets
Downloaded 67937 tweets
Downloaded 68037 tweets
Downloaded 68137 tweets
Downloaded 68237 tweets
Downloaded 68335 tweets
Downloaded 68435 tweets
Downloaded 68535 tweets
Downloaded 68635 tweets
Downloaded 68735 tweets
Downloaded 68835 tweets
Downloaded 68935 tweets
Downloaded 69035 tweets
Downloaded 69135 tweets
Downloaded 69235 tweets
Downloaded 69330 tweets
Downloaded 69430 tweets
Downloaded 69529 tweets
Downloaded 69629 tweets
Downloaded 69729 tweets
Downloaded 69829 tweets
Downloaded 69929 tweets
Downloaded 70029 tweets
Downloaded 70029 tweets, Saved to MongoDB election night

In [113]:
db.list_collection_names()

['election_tweets']

In [114]:
collection = db.election_tweets

In [55]:
collection.find().next()

{'_id': ObjectId('5be4ceaa17f0853db5033f7a'),
 'created_at': 'Fri Nov 09 00:02:33 +0000 2018',
 'id': 1060684028121092097,
 'id_str': '1060684028121092097',
 'full_text': "RT @MagniFieri: President @realDonaldTrump didnt fire Jeff Sessions the day after #Midterms2018 because he's afraid of you.\n\nTrump fired hi…",
 'truncated': False,
 'display_text_range': [0, 140],
 'entities': {'hashtags': [{'text': 'Midterms2018', 'indices': [82, 95]}],
  'symbols': [],
  'user_mentions': [{'screen_name': 'MagniFieri',
    'name': 'QAnon +++',
    'id': 803129760771637248,
    'id_str': '803129760771637248',
    'indices': [3, 14]},
   {'screen_name': 'realDonaldTrump',
    'name': 'Donald J. Trump',
    'id': 25073877,
    'id_str': '25073877',
    'indices': [26, 42]}],
  'urls': []},
 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'in_reply_to_screen_name': None,
 'user': {'id': 959140893260439552,
  'id_str': '959140893260439552',
  'name': 'ISTIM007',
  'screen_name': 'ISTIM007',
  'location': '',
  'description': '',
  'url': None,
  'entities': {'description': {'urls': []}},
  'protected': False,
  'followers_count': 169,
  'friends_count': 395,
  'listed_count': 1,
  'created_at': 'Thu Feb 01 19:06:23 +0000 2018',
  'favourites_count': 2643,
  'utc_offset': None,
  'time_zone': None,
  'geo_enabled': False,
  'verified': False,
  'statuses_count': 2288,
  'lang': 'en',
  'contributors_enabled': False,
  'is_translator': False,
  'is_translation_enabled': False,
  'profile_background_color': 'F5F8FA',
  'profile_background_image_url': None,
  'profile_background_image_url_https': None,
  'profile_background_tile': False,
  'profile_image_url': 'http://pbs.twimg.com/profile_images/963117250206199809/aUyuo_Yt_normal.jpg',
  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/963117250206199809/aUyuo_Yt_normal.jpg',
  'profile_link_color': '1DA1F2',
  'profile_sidebar_border_color': 'C0DEED',
  'profile_sidebar_fill_color': 'DDEEF6',
  'profile_text_color': '333333',
  'profile_use_background_image': True,
  'has_extended_profile': False,
  'default_profile': True,
  'default_profile_image': False,
  'following': False,
  'follow_request_sent': False,
  'notifications': False,
  'translator_type': 'none'},
 'geo': None,
 'coordinates': None,
 'place': None,
 'contributors': None,
 'retweeted_status': {'created_at': 'Wed Nov 07 23:29:05 +0000 2018',
  'id': 1060313216159567873,
  'id_str': '1060313216159567873',
  'full_text': "President @realDonaldTrump didnt fire Jeff Sessions the day after #Midterms2018 because he's afraid of you.\n\nTrump fired him today because now he's coming for you:\n\nHillary\nObama\nComey\nMcCabe\nDWS\nPodesta\nClapper\nBrennan\nStrzok\nPage\nOhr\nLynch\nHolder\nAbedin\nSoros\nJarrett\nKerry\nRice",
  'truncated': False,
  'display_text_range': [0, 280],
  'entities': {'hashtags': [{'text': 'Midterms2018', 'indices': [66, 79]}],
   'symbols': [],
   'user_mentions': [{'screen_name': 'realDonaldTrump',
     'name': 'Donald J. Trump',
     'id': 25073877,
     'id_str': '25073877',
     'indices': [10, 26]}],
   'urls': []},
  'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'in_reply_to_status_id': None,
  'in_reply_to_status_id_str': None,
  'in_reply_to_user_id': None,
  'in_reply_to_user_id_str': None,
  'in_reply_to_screen_name': None,
  'user': {'id': 803129760771637248,
   'id_str': '803129760771637248',
   'name': 'QAnon +++',
   'screen_name': 'MagniFieri',
   'location': 'United States',
   'description': 'Anti-Establishment Patriot. Trump Supporter. Nationalist. Truth Seeker. #WalkAway #WWG1WGA #FreeThinker',
   'url': None,
   'entities': {'description': {'urls': []}},
   'protected': False,
   'followers_count': 83468,
   'friends_count': 502,
   'listed_count': 263,
   'created_at': 'Mon Nov 28 06:53:51 +0000 2016',
   'favourites_count': 10299,
   'utc_offset': None,
   'time_zone': None,
   'geo_enabled': False,
   'verified': False,
   'statuses_count': 330,
   'lang': 'en',
   'contributors_enabled': False,
   'is_translator': False,
   'is_translation_enabled': False,
   'profile_background_color': '000000',
   'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
   'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
   'profile_background_tile': False,
   'profile_image_url': 'http://pbs.twimg.com/profile_images/943680597712654338/QW162UD-_normal.jpg',
   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/943680597712654338/QW162UD-_normal.jpg',
   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/803129760771637248/1513825344',
   'profile_link_color': 'ABB8C2',
   'profile_sidebar_border_color': '000000',
   'profile_sidebar_fill_color': '000000',
   'profile_text_color': '000000',
   'profile_use_background_image': False,
   'has_extended_profile': False,
   'default_profile': False,
   'default_profile_image': False,
   'following': False,
   'follow_request_sent': False,
   'notifications': False,
   'translator_type': 'none'},
  'geo': None,
  'coordinates': None,
  'place': None,
  'contributors': None,
  'is_quote_status': False,
  'retweet_count': 5761,
  'favorite_count': 10954,
  'favorited': False,
  'retweeted': False,
  'lang': 'en'},
 'is_quote_status': False,
 'retweet_count': 5761,
 'favorite_count': 0,
 'favorited': False,
 'retweeted': False,
 'lang': 'en'}

In [115]:

tweetdf = pd.DataFrame()
tweetdf['user'] = [tweet['user']['screen_name'] for tweet in collection.find()]
tweetdf['created_at'] = [datetime.strptime(tweet['created_at'], '%a %b %d %H:%M:%S %z %Y') for tweet in collection.find()] 
tweetdf['time_zone'] = [tweet['user']['time_zone'] for tweet in collection.find()]
text = []

for tweet in collection.find():
    try: 
        text.append(tweet['retweeted_status']['full_text'])
    except KeyError:       
        text.append(tweet['full_text'])

tweetdf['full_text'] = text


tweetdf['contains_url'] = tweetsDF['full_text'].str.contains('https', regex=True)*1
tweetdf['favorite_count'] = [tweet['favorite_count'] for tweet in collection.find()]
tweetdf['location'] = [tweet['place']['country'] if tweet['place'] != None else None 
                        for tweet in collection.find()]
text1 = []

for tweet in collection.find():
    try: 
        text1.append(tweet['retweeted_status']['user']['time_zone'])
    except KeyError:       
        text1.append(None)
tweetdf['rt_time_zone'] = text1


tweetdf['following_count'] = [tweet['user']['friends_count'] for tweet in collection.find()]
tweetdf['followers_count'] = [tweet['user']['followers_count'] for tweet in collection.find()]
tweetdf['retweet_count'] = [tweet['retweet_count'] for tweet in collection.find()]

# text2 = []

# for tweet in collection.find():
#     try: 
#         text2.append(tweet['retweeted_status']['place']['country'])
#     except KeyError:       
#         text2.append(None)
# tweetdf['rt_loc'] = text2

text3 = []

for tweet in collection.find():
    try: 
        text3.append(tweet['retweeted_status']['user']['followers_count'])
    except KeyError:       
        text3.append(None)
tweetdf['rt_follower_ct'] = text3
text4 = []
for tweet in collection.find():
    try: 
        text4.append(tweet['retweeted_status']['favorite_count'])
    except KeyError:       
        text4.append(None)
tweetdf['rt_fav_count'] = text4

# text5 = []
# for tweet in collection.find():
#     try: 
#         text5.append(tweet['entities']['hashtags']['text'])
#     except KeyError:       
#         text5.append(None)
# tweetdf['hashtag'] = text5

In [117]:
tweetsDF.head()

,user,created_at,full_text,truncated,contains_url,favorite_count
0,ISTIM007,2018-11-09 00:02:33+00:00,President @realDonaldTrump didnt fire Jeff Ses...,False,0,0
1,demmar__,2018-11-09 00:02:30+00:00,"Lucy McBath, a Georgia gun control activist wh...",False,1,0
2,AmaliaDiaz93,2018-11-09 00:02:27+00:00,HOLY CRAP! #FLORIDA VOTER Films #BrowardCounty...,False,1,0
3,avery1twins2,2018-11-09 00:02:25+00:00,"An observation: #Midterms2018 #Arizona, #Flori...",False,0,0
4,forgedbytrials_,2018-11-09 00:02:22+00:00,#chads getting bigger #StealingElections2018 #...,False,1,0

In [120]:
tweetdf.head()

,user,created_at,time_zone,full_text,contains_url,favorite_count,location,rt_time_zone,following_count,followers_count,retweet_count,rt_follower_ct,rt_fav_count
0,ISTIM007,2018-11-09 00:02:33+00:00,None,President @realDonaldTrump didnt fire Jeff Ses...,0,0,None,None,395,169,5761,83468.0,10954.0
1,demmar__,2018-11-09 00:02:30+00:00,None,"Lucy McBath, a Georgia gun control activist wh...",1,0,None,None,520,505,956,984883.0,2523.0
2,AmaliaDiaz93,2018-11-09 00:02:27+00:00,None,HOLY CRAP! #FLORIDA VOTER Films #BrowardCounty...,1,0,None,None,16003,16729,6,15159.0,3.0
3,avery1twins2,2018-11-09 00:02:25+00:00,None,"An observation: #Midterms2018 #Arizona, #Flori...",0,0,None,None,83,165,179,102494.0,313.0
4,forgedbytrials_,2018-11-09 00:02:22+00:00,None,#chads getting bigger #StealingElections2018 #...,1,0,None,None,4989,3045,0,NaN,NaN

In [124]:
tweetdf.to_csv('tweetdf.csv',index=False)

In [125]:
sam_df=pd.read_csv('tweetdf.csv')

In [126]:
sam_df.head()

,user,created_at,time_zone,full_text,contains_url,favorite_count,location,rt_time_zone,following_count,followers_count,retweet_count,rt_follower_ct,rt_fav_count
0,ISTIM007,2018-11-09 00:02:33+00:00,NaN,President @realDonaldTrump didnt fire Jeff Ses...,0,0,NaN,NaN,395,169,5761,83468.0,10954.0
1,demmar__,2018-11-09 00:02:30+00:00,NaN,"Lucy McBath, a Georgia gun control activist wh...",1,0,NaN,NaN,520,505,956,984883.0,2523.0
2,AmaliaDiaz93,2018-11-09 00:02:27+00:00,NaN,HOLY CRAP! #FLORIDA VOTER Films #BrowardCounty...,1,0,NaN,NaN,16003,16729,6,15159.0,3.0
3,avery1twins2,2018-11-09 00:02:25+00:00,NaN,"An observation: #Midterms2018 #Arizona, #Flori...",0,0,NaN,NaN,83,165,179,102494.0,313.0
4,forgedbytrials_,2018-11-09 00:02:22+00:00,NaN,#chads getting bigger #StealingElections2018 #...,1,0,NaN,NaN,4989,3045,0,NaN,NaN

In [75]:
df.head(30)

,user,created_at,rt_created_at,rt_loc,rt_tz,rt_favcount,rt_follower_ct,full_text,hashtag,truncated,favorite_count,location,time_zone,friends_count,retweet_count
0,NaN,NaN,NaN,id,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
1,NaN,NaN,NaN,url,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
2,NaN,NaN,NaN,place_type,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
3,NaN,NaN,NaN,name,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
4,NaN,NaN,NaN,full_name,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
5,NaN,NaN,NaN,country_code,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
6,NaN,NaN,NaN,country,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
7,NaN,NaN,NaN,contained_within,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
8,NaN,NaN,NaN,bounding_box,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
9,NaN,NaN,NaN,attributes,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,2083,30
10,NaN,NaN,NaN,id,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
11,NaN,NaN,NaN,url,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
12,NaN,NaN,NaN,place_type,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
13,NaN,NaN,NaN,name,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
14,NaN,NaN,NaN,full_name,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
15,NaN,NaN,NaN,country_code,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
16,NaN,NaN,NaN,country,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
17,NaN,NaN,NaN,contained_within,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
18,NaN,NaN,NaN,bounding_box,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
19,NaN,NaN,NaN,attributes,None,95,2644,Just two days after the #Midterms2018 hundreds...,None,False,0,None,None,3340,30
20,NaN,NaN,NaN,id,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
21,NaN,NaN,NaN,url,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
22,NaN,NaN,NaN,place_type,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
23,NaN,NaN,NaN,name,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
24,NaN,NaN,NaN,full_name,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
25,NaN,NaN,NaN,country_code,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
26,NaN,NaN,NaN,country,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
27,NaN,NaN,NaN,contained_within,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
28,NaN,NaN,NaN,bounding_box,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124
29,NaN,NaN,NaN,attributes,None,103,321,FLORIDA: If you submitted a provisional ballot...,None,False,0,None,None,2824,124